// TypeScript wrapper for chgdiff-wasm WASM bindings.
//
// Lazy-initialises the WASM module on first use.
// The pkg/ directory is generated by:
//   cd extensions/chgdiff-wasm && wasm-pack build --target web \
//     --out-dir ../../src/lib/electronic/chgdiff-wasm-pkg

import { browser } from '$app/environment'

type ChgdiffWasmModule = {
  /** wasm-bindgen init function — call once with the .wasm URL */
  default: (input: string | { module_or_path: string }) => Promise<void>
  /** Compute ρ_AB − ρ_A − ρ_B and return Gaussian cube text */
  compute_chgdiff: (ab: string, a: string, b: string) => string
}

let _module: ChgdiffWasmModule | null = null
let _init_promise: Promise<ChgdiffWasmModule> | null = null

async function ensure_ready(): Promise<ChgdiffWasmModule> {
  if (!browser) throw new Error(`chgdiff-wasm is browser-only`)
  if (_module) return _module
  if (_init_promise) return _init_promise

  _init_promise = (async () => {
    // WASM pkg generated by wasm-pack; may not exist until built
    // @ts-ignore — generated WASM package
    const mod = (await import(/* @vite-ignore */ `./chgdiff-wasm-pkg/chgdiff_wasm.js`)) as unknown as ChgdiffWasmModule

    const wasm_url_module = await import(
      /* @vite-ignore */ `./chgdiff-wasm-pkg/chgdiff_wasm_bg.wasm?url`
    )
    const wasm_url = wasm_url_module.default as string

    await mod.default({ module_or_path: wasm_url })
    _module = mod
    return mod
  })()

  return _init_promise
}

/**
 * Compute difference charge density (ρ_AB − ρ_A − ρ_B) from three CHGCAR
 * file contents and return a Gaussian cube format string.
 *
 * Runs entirely in the browser via WebAssembly — no backend required.
 * Large files (>50 MB) will block the main thread during parsing.
 */
export async function compute_chgdiff(
  content_ab: string,
  content_a: string,
  content_b: string,
): Promise<string> {
  const mod = await ensure_ready()
  return mod.compute_chgdiff(content_ab, content_a, content_b)
}
