<script lang="ts">
  import type { AnyStructure } from '$lib'
  import { Icon } from '$lib'
  import {
    generate_amber_mdin, apply_amber_preset,
    MLP_MODELS, type AmberPreset,
  } from '$lib/structure/export/amber-export'

  let {
    structure = undefined,
    prefix = $bindable('amber_job'),
    generated_output = $bindable<Record<string, string>>({}),
    generation_error = $bindable<string | null>(null),
    active_file = $bindable(''),
  }: {
    structure?: AnyStructure
    prefix?: string
    generated_output?: Record<string, string>
    generation_error?: string | null
    active_file?: string
  } = $props()

  // ====== AMBER state ======
  let job_type = $state<'md' | 'minimize'>('md')
  let title = $state('CatGO AMBER job')

  // MD
  let nstlim = $state(5000000)
  let dt = $state(0.0001)
  // Minimization
  let maxcyc = $state(5000)
  let ncyc = $state(2500)
  let drms = $state(0.0001)

  // Restart
  let irest = $state(1)

  // Thermostat
  let ntt = $state(0)
  let temp0 = $state(300.0)
  let tempi = $state(300.0)
  let gamma_ln = $state(2.0)

  // Periodicity
  let ntb = $state(0)
  let cut = $state(9999.0)

  // SHAKE
  let ntc = $state(1)
  let ntf = $state(1)

  // Output
  let ntpr = $state(1000)
  let ntwe = $state(1000)
  let ntwx = $state(10000)
  let ntwv = $state(0)
  let ntwr = $state(100000)
  let ioutfm = $state(1)
  let ntxo = $state(2)

  // Barostat
  let ntp = $state(0)
  let barostat = $state(2)
  let pres0 = $state(1.0)

  // ML/MM
  let use_mlp = $state(true)
  let mlp_model = $state('macepol_l')
  let animask = $state('')
  let mlp_shake = $state(1)
  let gpu_id = $state(0)
  let mlp_embedding = $state(2)
  let mlp_multipole = $state(1)
  let mlp_polar = $state(2)
  let adjust_q = $state(1)

  // Extra
  let extra_cntrl = $state('')
  let extra_mlp = $state('')

  // Topology / restart file paths (for reference in generated output)
  let topology_path = $state('')
  let restart_path = $state('')

  let time_display = $derived.by(() => {
    if (job_type === 'minimize') return ``
    const time_ps = nstlim * dt
    if (time_ps >= 1000) return `${(time_ps / 1000).toFixed(2)} ns`
    return `${time_ps.toFixed(2)} ps`
  })

  function apply_preset(preset: AmberPreset) {
    generated_output = {}
    const p = apply_amber_preset(preset)
    if (p.job_type !== undefined) job_type = p.job_type
    if (p.nstlim !== undefined) nstlim = p.nstlim
    if (p.dt !== undefined) dt = p.dt
    if (p.maxcyc !== undefined) maxcyc = p.maxcyc
    if (p.ncyc !== undefined) ncyc = p.ncyc
    if (p.irest !== undefined) irest = p.irest
    if (p.ntt !== undefined) ntt = p.ntt
    if (p.temp0 !== undefined) { temp0 = p.temp0; tempi = p.temp0 }
    if (p.gamma_ln !== undefined) gamma_ln = p.gamma_ln
    if (p.ntb !== undefined) ntb = p.ntb
    if (p.cut !== undefined) cut = p.cut
    if (p.ntc !== undefined) ntc = p.ntc
    if (p.ntf !== undefined) ntf = p.ntf
    if (p.use_mlp !== undefined) use_mlp = p.use_mlp
    if (p.mlp_model !== undefined) mlp_model = p.mlp_model
    if (p.ntp !== undefined) ntp = p.ntp
    if (p.barostat !== undefined) barostat = p.barostat
    if (p.pres0 !== undefined) pres0 = p.pres0
  }

  function generate() {
    generation_error = null
    try {
      const mdin = generate_amber_mdin({
        title, job_type, nstlim, dt, maxcyc, ncyc, drms,
        irest, ntt, temp0, tempi, gamma_ln,
        ntb, cut, ntc, ntf,
        ntpr, ntwe, ntwx, ntwv, ntwr, ioutfm, ntxo,
        ntp, barostat, pres0,
        use_mlp, mlp_model, animask, mlp_shake, gpu_id,
        mlp_embedding, mlp_multipole, mlp_polar, adjust_q,
        extra_cntrl, extra_mlp,
      })

      const files: Record<string, string> = { mdin }

      // Generate a shell run script
      const run_lines = [
        `#!/bin/bash`,
        `# AMBER ${job_type === 'minimize' ? 'minimization' : 'MD'} run script`,
        `# Generated by CatGO`,
        ``,
      ]
      if (use_mlp) {
        run_lines.push(`# ML/MM run with sander`)
        run_lines.push(`sander -O \\`)
      } else {
        run_lines.push(`# Classical run with pmemd (or sander)`)
        run_lines.push(`pmemd -O \\`)
      }
      run_lines.push(`  -i mdin \\`)
      run_lines.push(`  -o ${prefix}.out \\`)
      run_lines.push(`  -p ${topology_path || 'prmtop'} \\`)
      run_lines.push(`  -c ${restart_path || 'inpcrd'} \\`)
      run_lines.push(`  -r ${prefix}.rst7 \\`)
      run_lines.push(`  -x ${prefix}.nc \\`)
      run_lines.push(`  -e ${prefix}.mden \\`)
      run_lines.push(`  -inf ${prefix}.mdinfo`)

      files[`run_${prefix}.sh`] = run_lines.join('\n') + '\n'

      generated_output = files
      active_file = 'mdin'
    } catch (e) {
      generation_error = e instanceof Error ? e.message : `Failed to generate AMBER input`
    }
  }
</script>

<div class="section-content calc-section">
  <div style="font-size: 0.78em; color: var(--info-color, #5b9bd5); padding: 0.4em 0.5em; margin-bottom: 0.5em; background: light-dark(rgba(91,155,213,0.08), rgba(91,155,213,0.1)); border-radius: 4px; border-left: 3px solid var(--info-color, #5b9bd5);">
    Generates mdin (control input) and a run script for AMBER sander/pmemd.
    Topology (.prmtop) and coordinates (.rst7/.inpcrd) must be prepared separately.
  </div>

  <!-- Preset buttons -->
  <div style="display: flex; gap: 0.25rem; margin-bottom: 0.5em; flex-wrap: wrap;">
    <button class="preset-btn" onclick={() => apply_preset('mlmm_md')} title="ML/MM MD (NVE, 0.1 fs)">ML/MM MD</button>
    <button class="preset-btn" onclick={() => apply_preset('mlmm_min')} title="ML/MM Minimization">ML/MM Min</button>
    <button class="preset-btn" onclick={() => apply_preset('classical_md')} title="Classical MD (Langevin NVT, 2 fs)">Classical MD</button>
    <button class="preset-btn" onclick={() => apply_preset('classical_min')} title="Classical Minimization">Classical Min</button>
    <button class="preset-btn" onclick={() => apply_preset('nvt_langevin')} title="NVT Langevin (300K, 2 fs)">NVT</button>
    <button class="preset-btn" onclick={() => apply_preset('npt_langevin')} title="NPT Langevin (300K, 1 bar)">NPT</button>
  </div>

  <div class="param-row">
    <span>Prefix</span>
    <input type="text" bind:value={prefix} class="text-input" />
  </div>
  <div class="param-row">
    <span>Job Type</span>
    <select bind:value={job_type} onchange={() => generated_output = {}}>
      <option value="md">Molecular Dynamics</option>
      <option value="minimize">Minimization</option>
    </select>
  </div>
  <div class="param-row">
    <span>Title</span>
    <input type="text" bind:value={title} class="text-input" />
  </div>

  <!-- MD settings -->
  {#if job_type === 'md'}
    <div class="param-row">
      <span>nstlim <span class="param-help" title="Number of MD steps">?</span></span>
      <input type="number" min="1" bind:value={nstlim} />
      <span style="font-size: 0.8em; opacity: 0.7; margin-left: 4px;">{time_display}</span>
    </div>
    <div class="param-row">
      <span>dt (ps) <span class="param-help" title="Timestep. Use 0.0001 ps (0.1 fs) for ML/MM or 0.002 ps (2 fs) for classical with SHAKE">?</span></span>
      <input type="number" step="0.0001" min="0.00001" bind:value={dt} />
    </div>
  {:else}
    <div class="param-row">
      <span>maxcyc <span class="param-help" title="Maximum minimization cycles">?</span></span>
      <input type="number" min="1" bind:value={maxcyc} />
    </div>
    <div class="param-row">
      <span>ncyc <span class="param-help" title="Steepest descent steps before switching to conjugate gradient">?</span></span>
      <input type="number" min="0" bind:value={ncyc} />
    </div>
    <div class="param-row">
      <span>drms <span class="param-help" title="RMS gradient convergence criterion">?</span></span>
      <input type="number" step="0.0001" min="0" bind:value={drms} />
    </div>
  {/if}

  <!-- Restart -->
  <div class="param-row">
    <span>irest <span class="param-help" title="0 = new run, 1 = restart from coordinates + velocities">?</span></span>
    <select bind:value={irest}>
      <option value={0}>0 (new)</option>
      <option value={1}>1 (restart)</option>
    </select>
  </div>

  <!-- Thermostat -->
  {#if job_type === 'md'}
    <details class="advanced-details" open>
      <summary>Thermostat</summary>
      <div class="param-row">
        <span>ntt <span class="param-help" title="0=NVE, 1=Berendsen, 2=Andersen, 3=Langevin">?</span></span>
        <select bind:value={ntt}>
          <option value={0}>0 (NVE)</option>
          <option value={1}>1 (Berendsen)</option>
          <option value={2}>2 (Andersen)</option>
          <option value={3}>3 (Langevin)</option>
        </select>
      </div>
      {#if ntt >= 1}
        <div class="param-row">
          <span>temp0 (K)</span>
          <input type="number" step="0.1" min="0" bind:value={temp0} />
        </div>
        <div class="param-row">
          <span>tempi (K)</span>
          <input type="number" step="0.1" min="0" bind:value={tempi} />
        </div>
      {/if}
      {#if ntt === 3}
        <div class="param-row">
          <span>gamma_ln (ps<sup>-1</sup>) <span class="param-help" title="Langevin collision frequency">?</span></span>
          <input type="number" step="0.1" min="0" bind:value={gamma_ln} />
        </div>
      {/if}
    </details>
  {/if}

  <!-- Periodicity & cutoff -->
  <details class="advanced-details" open>
    <summary>Periodicity & Cutoff</summary>
    <div class="param-row">
      <span>ntb <span class="param-help" title="0=no PBC, 1=constant volume, 2=constant pressure">?</span></span>
      <select bind:value={ntb}>
        <option value={0}>0 (no PBC)</option>
        <option value={1}>1 (const volume)</option>
        <option value={2}>2 (const pressure)</option>
      </select>
    </div>
    <div class="param-row">
      <span>cut ({'\u00C5'}) <span class="param-help" title="Nonbonded cutoff. 9999 for non-periodic, ~10 for periodic">?</span></span>
      <input type="number" step="0.1" min="0" bind:value={cut} />
    </div>
  </details>

  <!-- SHAKE -->
  <details class="advanced-details">
    <summary>SHAKE Constraints</summary>
    <div class="param-row">
      <span>ntc <span class="param-help" title="1=no SHAKE, 2=bonds with H, 3=all bonds">?</span></span>
      <select bind:value={ntc}>
        <option value={1}>1 (none)</option>
        <option value={2}>2 (H bonds)</option>
        <option value={3}>3 (all bonds)</option>
      </select>
    </div>
    <div class="param-row">
      <span>ntf <span class="param-help" title="Force evaluation: match ntc. 1=complete, 2=omit H bonds, 3=omit all bonds">?</span></span>
      <select bind:value={ntf}>
        <option value={1}>1 (complete)</option>
        <option value={2}>2 (omit H bonds)</option>
        <option value={3}>3 (omit all bonds)</option>
      </select>
    </div>
  </details>

  <!-- Barostat -->
  {#if job_type === 'md'}
    <details class="advanced-details" open={ntp > 0}>
      <summary>Barostat (NPT)</summary>
      <div class="param-row">
        <span>ntp <span class="param-help" title="0=no pressure control, 1=isotropic, 2=anisotropic">?</span></span>
        <select bind:value={ntp}>
          <option value={0}>0 (off)</option>
          <option value={1}>1 (isotropic)</option>
          <option value={2}>2 (anisotropic)</option>
        </select>
      </div>
      {#if ntp > 0}
        <div class="param-row">
          <span>barostat <span class="param-help" title="1=Berendsen, 2=Monte Carlo">?</span></span>
          <select bind:value={barostat}>
            <option value={1}>1 (Berendsen)</option>
            <option value={2}>2 (Monte Carlo)</option>
          </select>
        </div>
        <div class="param-row">
          <span>pres0 (bar)</span>
          <input type="number" step="0.1" min="0" bind:value={pres0} />
        </div>
      {/if}
    </details>
  {/if}

  <!-- ML/MM -->
  <details class="advanced-details" open={use_mlp}>
    <summary>ML/MM Potential</summary>
    <label class="checkbox-row">
      <input type="checkbox" bind:checked={use_mlp} /> Enable ML potential (ifmlp=1)
    </label>
    {#if use_mlp}
      <div class="param-row">
        <span>Model</span>
        <select bind:value={mlp_model}>
          {#each Object.keys(MLP_MODELS) as model}
            <option value={model}>{model}</option>
          {/each}
        </select>
      </div>
      <div class="param-row">
        <span>animask <span class="param-help" title="Atom mask for ML region, e.g. ':1-100'">?</span></span>
        <input type="text" bind:value={animask} class="text-input" placeholder=":1-100" />
      </div>
      <div class="param-row">
        <span>gpu_id</span>
        <input type="number" min="0" bind:value={gpu_id} />
      </div>
      <div class="param-row">
        <span>mlp_embedding <span class="param-help" title="1=OFF, 2=ON">?</span></span>
        <select bind:value={mlp_embedding}>
          <option value={1}>1 (off)</option>
          <option value={2}>2 (on)</option>
        </select>
      </div>
      <div class="param-row">
        <span>mlp_multipole</span>
        <select bind:value={mlp_multipole}>
          <option value={0}>0 (off)</option>
          <option value={1}>1 (on)</option>
        </select>
      </div>
      <div class="param-row">
        <span>mlp_polar <span class="param-help" title="0=no polarization, 1=charge, 2=dipole">?</span></span>
        <select bind:value={mlp_polar}>
          <option value={0}>0 (off)</option>
          <option value={1}>1 (charge)</option>
          <option value={2}>2 (dipole)</option>
        </select>
      </div>
      <div class="param-row">
        <span>adjust_q</span>
        <select bind:value={adjust_q}>
          <option value={0}>0 (off)</option>
          <option value={1}>1 (on)</option>
        </select>
      </div>
      <div class="param-row">
        <span>mlp_shake</span>
        <select bind:value={mlp_shake}>
          <option value={0}>0 (off)</option>
          <option value={1}>1 (on)</option>
        </select>
      </div>
    {/if}
  </details>

  <!-- Output -->
  <details class="advanced-details">
    <summary>Output Frequencies</summary>
    <div class="param-row"><span>ntpr <span class="param-help" title="Energy info every N steps">?</span></span><input type="number" min="1" bind:value={ntpr} /></div>
    <div class="param-row"><span>ntwe <span class="param-help" title="Energy file every N steps">?</span></span><input type="number" min="1" bind:value={ntwe} /></div>
    <div class="param-row"><span>ntwx <span class="param-help" title="Trajectory every N steps">?</span></span><input type="number" min="1" bind:value={ntwx} /></div>
    <div class="param-row"><span>ntwv <span class="param-help" title="Velocity every N steps (0=off)">?</span></span><input type="number" min="0" bind:value={ntwv} /></div>
    <div class="param-row"><span>ntwr <span class="param-help" title="Restart file every N steps">?</span></span><input type="number" min="1" bind:value={ntwr} /></div>
  </details>

  <!-- File paths (reference) -->
  <details class="advanced-details">
    <summary>File Paths (for run script)</summary>
    <div class="param-row">
      <span>Topology</span>
      <input type="text" bind:value={topology_path} class="text-input" placeholder="prmtop" />
    </div>
    <div class="param-row">
      <span>Restart/Coord</span>
      <input type="text" bind:value={restart_path} class="text-input" placeholder="inpcrd" />
    </div>
  </details>

  <!-- Extra parameters -->
  <details class="advanced-details">
    <summary>Extra Parameters</summary>
    <div style="margin-bottom: 4px;">
      <span style="font-size: 0.8em; opacity: 0.7;">Extra &cntrl lines:</span>
      <textarea bind:value={extra_cntrl} rows="2" class="extra-textarea" placeholder="key = value,"></textarea>
    </div>
    {#if use_mlp}
      <div>
        <span style="font-size: 0.8em; opacity: 0.7;">Extra &mlp lines:</span>
        <textarea bind:value={extra_mlp} rows="2" class="extra-textarea" placeholder="key=value,"></textarea>
      </div>
    {/if}
  </details>

  <div class="button-group">
    <button class="generate-btn" onclick={generate}>
      <Icon icon="Zap" style="width: 14px; height: 14px" /> Generate
    </button>
  </div>
</div>

<style>
  .calc-section { max-height: 400px; overflow-y: auto; }
  .param-row span { flex-shrink: 0; }
  .param-help {
    display: inline-flex; align-items: center; justify-content: center;
    width: 13px; height: 13px; font-size: 9px; font-weight: 700;
    border-radius: 50%; background: var(--btn-bg, light-dark(rgba(0,0,0,0.08), rgba(255,255,255,0.1)));
    color: var(--text-color-muted); cursor: help; flex-shrink: 0; margin-left: 2px;
    border: 1px solid var(--btn-bg, light-dark(rgba(0,0,0,0.12), rgba(255,255,255,0.15)));
    line-height: 1; vertical-align: middle;
  }
  .param-help:hover { background: var(--btn-bg-hover, light-dark(rgba(0,0,0,0.15), rgba(255,255,255,0.2))); color: var(--text-color); }
  .param-row input[type="number"], .param-row input[type="text"], .param-row select { width: 100px; text-align: right; flex-shrink: 0; }
  .text-input { flex: 1 !important; width: auto !important; min-width: 60px; }
  .advanced-details { background: light-dark(rgba(0,0,0,0.02), rgba(255,255,255,0.02)); border-radius: 4px; padding: 0.4em; margin: 0.5em 0; }
  .button-group { margin-top: 0.6em; }
  .generate-btn { display: flex; align-items: center; gap: 5px; padding: 5px 10px; background: var(--accent-color, #007acc); color: white; border: none; border-radius: 4px; cursor: pointer; }
  .generate-btn:hover { filter: brightness(1.1); }
  .preset-btn { padding: 2px 8px; font-size: 0.8em; background: rgba(59,130,246,0.3); border: 1px solid rgba(59,130,246,0.5); border-radius: 3px; cursor: pointer; color: var(--accent-color); white-space: nowrap; }
  .preset-btn:hover { background: rgba(59,130,246,0.5); }
  .checkbox-row { display: flex; align-items: center; gap: 6px; font-size: 0.9em; cursor: pointer; padding: 2px 0; }
  .extra-textarea { width: 100%; font-size: 0.85em; font-family: monospace; resize: vertical; border: 1px solid var(--btn-bg); border-radius: 3px; background: transparent; color: inherit; padding: 4px; }
</style>
