/**
 * GROMACS input file generation.
 */
import type { AnyStructure, PymatgenStructure, BondPair } from '$lib'
import { atom_radii as detect_bonds_atom_radii } from '$lib/structure/bonding'
import { get_atom_mass } from './common-export'

export interface GromacsParams {
  prefix: string
  sim_type: 'em' | 'eq_nvt' | 'eq_npt' | 'prod_npt' | 'prod_nvt' | 'heat_npt' | 'gas_phase'
  dt: number
  nsteps: number
  nsteps_display: string
  emtol: number
  emstep: number
  tcoupl: string
  ref_t: number
  tau_t: number
  pcoupl: string
  pcoupltype: string
  ref_p: number
  tau_p: number
  coulombtype: string
  rcoulomb: number
  rvdw: number
  pbc: string
  dispcorr: string
  nstlog: number
  nstenergy: number
  nstxout_compressed: number
  constraints: string
  gen_vel: string
  gen_temp: number
  posres: boolean
  anneal_time: string
  anneal_temp: string
}

export type GromacsPreset = 'em' | 'eq_nvt' | 'eq_npt' | 'prod_npt' | 'heat_npt' | 'gas_phase'

export function apply_gmx_preset(preset: GromacsPreset): Partial<GromacsParams> {
  if (preset === 'em') {
    return { sim_type: 'em', nsteps: 50000, emtol: 1000, emstep: 0.01 }
  } else if (preset === 'eq_nvt') {
    return {
      sim_type: 'eq_nvt', dt: 0.002, nsteps: 50000,
      tcoupl: 'V-rescale', ref_t: 300, tau_t: 0.1,
      pcoupl: 'no', gen_vel: 'yes', gen_temp: 300,
      constraints: 'hbonds', posres: true,
    }
  } else if (preset === 'eq_npt') {
    return {
      sim_type: 'eq_npt', dt: 0.002, nsteps: 50000,
      tcoupl: 'V-rescale', ref_t: 300, tau_t: 0.1,
      pcoupl: 'parrinello-rahman', ref_p: 1.0, tau_p: 2.0,
      gen_vel: 'no', constraints: 'hbonds', posres: true,
    }
  } else if (preset === 'prod_npt') {
    return {
      sim_type: 'prod_npt', dt: 0.002, nsteps: 1000000,
      tcoupl: 'V-rescale', ref_t: 300, tau_t: 0.1,
      pcoupl: 'parrinello-rahman', ref_p: 1.0, tau_p: 2.0,
      gen_vel: 'no', constraints: 'hbonds', posres: false,
    }
  } else if (preset === 'heat_npt') {
    return {
      sim_type: 'heat_npt', dt: 0.002, nsteps: 100000,
      tcoupl: 'V-rescale', tau_t: 0.1,
      pcoupl: 'parrinello-rahman', ref_p: 1.0, tau_p: 2.0,
      gen_vel: 'yes', gen_temp: 0,
      anneal_time: '0 100', anneal_temp: '0 298.15',
    }
  } else {
    return {
      sim_type: 'gas_phase', dt: 0.001, nsteps: 500000,
      tcoupl: 'V-rescale', ref_t: 300, tau_t: 0.1,
      pcoupl: 'no', pbc: 'no', coulombtype: 'Cut-off',
      constraints: 'none', gen_vel: 'yes', gen_temp: 300,
    }
  }
}

export function generate_gromacs_input(structure: AnyStructure, params: GromacsParams): Record<string, string> {
  if (!structure) throw new Error('No structure')

  let mdp = ``
  mdp += `; GROMACS .mdp file generated by CatGo\n`
  mdp += `; Simulation type: ${params.sim_type}\n\n`

  if (params.sim_type === `em`) {
    mdp += `integrator  = steep\n`
    mdp += `nsteps      = ${params.nsteps}\n`
    mdp += `emtol       = ${params.emtol}\n`
    mdp += `emstep      = ${params.emstep}\n`
  } else {
    mdp += `integrator  = md\n`
    mdp += `dt          = ${params.dt}\n`
    mdp += `nsteps      = ${params.nsteps}  ; ${params.nsteps_display}\n`
  }

  mdp += `\n; Output\n`
  mdp += `nstlog              = ${params.nstlog}\n`
  mdp += `nstenergy           = ${params.nstenergy}\n`
  mdp += `nstxout-compressed  = ${params.nstxout_compressed}\n`

  mdp += `\n; Electrostatics & VdW\n`
  mdp += `coulombtype = ${params.coulombtype}\n`
  mdp += `rcoulomb    = ${params.rcoulomb}\n`
  mdp += `rvdw        = ${params.rvdw}\n`
  mdp += `pbc         = ${params.pbc}\n`
  mdp += `DispCorr    = ${params.dispcorr}\n`

  if (params.constraints !== `none`) {
    mdp += `\n; Constraints\n`
    mdp += `constraints     = ${params.constraints}\n`
    mdp += `constraint-algorithm = lincs\n`
  }

  if (params.sim_type !== `em`) {
    mdp += `\n; Temperature coupling\n`
    mdp += `tcoupl  = ${params.tcoupl}\n`
    mdp += `tc-grps = System\n`
    mdp += `ref_t   = ${params.ref_t}\n`
    mdp += `tau_t   = ${params.tau_t}\n`

    if (params.pcoupl !== `no`) {
      mdp += `\n; Pressure coupling\n`
      mdp += `pcoupl      = ${params.pcoupl}\n`
      mdp += `pcoupltype  = ${params.pcoupltype}\n`
      mdp += `ref_p       = ${params.ref_p}\n`
      mdp += `tau_p       = ${params.tau_p}\n`
      mdp += `compressibility = 4.5e-5\n`
    }

    if (params.gen_vel === `yes`) {
      mdp += `\n; Velocity generation\n`
      mdp += `gen_vel  = yes\n`
      mdp += `gen_temp = ${params.gen_temp}\n`
    }

    if (params.posres) {
      mdp += `\ndefine = -DPOSRES\n`
    }

    if (params.sim_type === `heat_npt`) {
      mdp += `\n; Simulated annealing\n`
      mdp += `annealing       = single\n`
      const n_points = params.anneal_time.trim().split(/\s+/).length
      mdp += `annealing-npoints = ${n_points}\n`
      mdp += `annealing-time  = ${params.anneal_time}\n`
      mdp += `annealing-temp  = ${params.anneal_temp}\n`
    }
  }

  const mdp_fname = `${params.prefix}.mdp`

  // Generate .gro coordinate file
  const sites = structure.sites
  const n_atoms = sites.length
  let gro = `Generated by CatGo\n`
  gro += `${n_atoms}\n`
  for (let i = 0; i < n_atoms; i++) {
    const site = sites[i]
    const el = site.species?.[0]?.element ?? `X`
    const [x, y, z] = site.xyz ?? [0, 0, 0]
    const res_nr = String(1).padStart(5)
    const res_name = `MOL`.padEnd(5)
    const atom_name = el.padEnd(5)
    const atom_nr = String(i + 1).padStart(5)
    gro += `${res_nr}${res_name}${atom_name}${atom_nr}${(x / 10).toFixed(3).padStart(8)}${(y / 10).toFixed(3).padStart(8)}${(z / 10).toFixed(3).padStart(8)}\n`
  }
  // Box vectors (convert from Angstrom to nm)
  const lat = (structure as PymatgenStructure).lattice?.matrix
  if (lat) {
    const [ax, ay, az] = lat[0].map((v: number) => v / 10)
    const [bx, by, bz] = lat[1].map((v: number) => v / 10)
    const [cx, cy, cz] = lat[2].map((v: number) => v / 10)
    gro += `${ax.toFixed(5).padStart(10)} ${by.toFixed(5).padStart(9)} ${cz.toFixed(5).padStart(9)} ${ay.toFixed(5).padStart(9)} ${az.toFixed(5).padStart(9)} ${bx.toFixed(5).padStart(9)} ${bz.toFixed(5).padStart(9)} ${cx.toFixed(5).padStart(9)} ${cy.toFixed(5).padStart(9)}\n`
  } else {
    gro += `   5.00000   5.00000   5.00000\n`
  }

  // Generate .top topology file with real topology from bond detection
  const bond_pairs: BondPair[] = detect_bonds_atom_radii(structure)
  const adjacency = new Map<number, Set<number>>()
  const bond_set = new Set<string>()
  for (const bp of bond_pairs) {
    if (bp.bond_type === `hydrogen`) continue
    const a = bp.site_idx_1, b = bp.site_idx_2
    if (!adjacency.has(a)) adjacency.set(a, new Set())
    if (!adjacency.has(b)) adjacency.set(b, new Set())
    adjacency.get(a)!.add(b)
    adjacency.get(b)!.add(a)
    const key = a < b ? `${a}-${b}` : `${b}-${a}`
    bond_set.add(key)
  }

  // Derive angles
  const angle_list: [number, number, number][] = []
  const angle_set = new Set<string>()
  for (const [b, neighbors] of adjacency) {
    const nbrs = Array.from(neighbors).sort((x, y) => x - y)
    for (let i = 0; i < nbrs.length; i++) {
      for (let j = i + 1; j < nbrs.length; j++) {
        const key = `${nbrs[i]}-${b}-${nbrs[j]}`
        if (!angle_set.has(key)) {
          angle_set.add(key)
          angle_list.push([nbrs[i], b, nbrs[j]])
        }
      }
    }
  }

  // Derive dihedrals
  const dihedral_list: [number, number, number, number][] = []
  const dihedral_set = new Set<string>()
  for (const bond_key of bond_set) {
    const [b, c] = bond_key.split(`-`).map(Number)
    const b_nbrs = adjacency.get(b) ?? new Set<number>()
    const c_nbrs = adjacency.get(c) ?? new Set<number>()
    for (const a of b_nbrs) {
      if (a === c) continue
      for (const d of c_nbrs) {
        if (d === b || d === a) continue
        const key = a < d ? `${a}-${b}-${c}-${d}` : `${d}-${c}-${b}-${a}`
        if (!dihedral_set.has(key)) {
          dihedral_set.add(key)
          dihedral_list.push(a < d ? [a, b, c, d] : [d, c, b, a])
        }
      }
    }
  }

  // Collect unique atom types
  const atom_types = new Map<string, { mass: number; count: number }>()
  for (const site of sites) {
    const el = site.species?.[0]?.element ?? `X`
    if (!atom_types.has(el)) {
      atom_types.set(el, { mass: get_atom_mass(el), count: 0 })
    }
    atom_types.get(el)!.count++
  }

  let top = `; Topology file generated by CatGo\n`
  top += `; Bonds, angles, and dihedrals extracted from structure connectivity\n`
  top += `; NOTE: Force field parameters (charges, LJ, force constants) are placeholders.\n`
  top += `; Assign proper parameters via a force field tool (AmberTools, CHARMM-GUI, etc.)\n\n`
  top += `[ defaults ]\n`
  top += `; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ\n`
  top += `  1       2          yes        0.5      0.8333\n\n`
  top += `[ atomtypes ]\n`
  top += `; name  at.num  mass        charge  ptype  sigma      epsilon\n`
  for (const [el, info] of atom_types) {
    top += `  ${el.padEnd(6)} 0     ${info.mass.toFixed(4).padStart(10)}  0.0000  A      0.000000   0.000000\n`
  }
  top += `\n[ moleculetype ]\n`
  top += `; name  nrexcl\n`
  top += `  MOL   3\n\n`
  top += `[ atoms ]\n`
  top += `; nr  type  resnr  residue  atom  cgnr  charge    mass\n`
  for (let i = 0; i < n_atoms; i++) {
    const el = sites[i].species?.[0]?.element ?? `X`
    const mass = atom_types.get(el)?.mass ?? 0
    top += `  ${String(i + 1).padEnd(5)} ${el.padEnd(6)} 1      MOL      ${el.padEnd(6)} ${String(i + 1).padEnd(5)} 0.000000  ${mass.toFixed(4)}\n`
  }

  if (bond_set.size > 0) {
    top += `\n[ bonds ]\n`
    top += `; ai  aj  funct  b0 (nm)  kb (kJ/mol/nm^2)\n`
    for (const key of bond_set) {
      const [a, b] = key.split(`-`).map(Number)
      const pa = sites[a].xyz, pb = sites[b].xyz
      const bl = Math.hypot(pa[0] - pb[0], pa[1] - pb[1], pa[2] - pb[2]) / 10
      top += `  ${String(a + 1).padEnd(5)} ${String(b + 1).padEnd(5)} 1      ${bl.toFixed(4).padStart(8)}  100000.0\n`
    }
  }

  if (angle_list.length > 0) {
    top += `\n[ angles ]\n`
    top += `; ai  aj  ak  funct  theta0 (deg)  ktheta (kJ/mol/rad^2)\n`
    for (const [a, b, c] of angle_list) {
      const pa = sites[a].xyz, pb = sites[b].xyz, pc = sites[c].xyz
      const v1: [number, number, number] = [pa[0] - pb[0], pa[1] - pb[1], pa[2] - pb[2]]
      const v2: [number, number, number] = [pc[0] - pb[0], pc[1] - pb[1], pc[2] - pb[2]]
      const dot = v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2]
      const n1 = Math.hypot(...v1), n2 = Math.hypot(...v2)
      const ang = (n1 > 0 && n2 > 0) ? Math.acos(Math.max(-1, Math.min(1, dot / (n1 * n2)))) * 180 / Math.PI : 0
      top += `  ${String(a + 1).padEnd(5)} ${String(b + 1).padEnd(5)} ${String(c + 1).padEnd(5)} 1      ${ang.toFixed(2).padStart(8)}  500.0\n`
    }
  }

  if (dihedral_list.length > 0) {
    top += `\n[ dihedrals ]\n`
    top += `; ai  aj  ak  al  funct  phi0 (deg)  kphi  multiplicity\n`
    for (const [a, b, c, d] of dihedral_list) {
      top += `  ${String(a + 1).padEnd(5)} ${String(b + 1).padEnd(5)} ${String(c + 1).padEnd(5)} ${String(d + 1).padEnd(5)} 1      0.00      1.0  3\n`
    }
  }

  top += `\n[ system ]\n`
  top += `${params.prefix}\n\n`
  top += `[ molecules ]\n`
  top += `; compound  nmols\n`
  top += `  MOL       1\n`

  const gro_fname = `${params.prefix}.gro`
  const top_fname = `${params.prefix}.top`
  return { [mdp_fname]: mdp, [gro_fname]: gro, [top_fname]: top }
}
