import type { NodeDefinition } from '../../workflow-types'

export const dos_analysis: NodeDefinition = {
  type: `dos_analysis`,
  label: `DOS Analysis`,
  color: `#db2777`,
  icon: `\u{1F4CA}`,
  category: `Analysis`,
  description: `Density of states analysis from VASP output`,
  inputs: [`data`],
  outputs: [`result`],
  default_params: { source: `parent_step`, sigma: 0.05, emin: -10, emax: 6, ngrid: 2000, atom_indices: ``, element_filter: ``, orbital_channels: `total`, d_band: true, d_band_occupied_only: true },
  help_text: `**DOS Analysis** — Density of states post-processing.`,
  param_schema: [
    { key: `source`, label: `Data Source`, type: `select`, default: `parent_step`, group: `Analysis`,
      options: [
        { label: `From parent step output`, value: `parent_step` },
        { label: `From remote file`, value: `remote` },
      ],
    },
    // --- DOS parameters ---
    { key: `sigma`, label: `Broadening \u03C3 (eV)`, type: `number`, default: 0.05, group: `DOS Parameters`,
      min: 0.001, max: 1.0, step: 0.01,
      help: `Gaussian broadening width for DOS smoothing.`,
    },
    { key: `emin`, label: `Energy Min (eV)`, type: `number`, default: -10, group: `DOS Parameters`,
      min: -30, max: 0, step: 1,
      help: `Lower bound of energy range (relative to Fermi level).`,
    },
    { key: `emax`, label: `Energy Max (eV)`, type: `number`, default: 6, group: `DOS Parameters`,
      min: 0, max: 30, step: 1,
      help: `Upper bound of energy range (relative to Fermi level).`,
    },
    { key: `ngrid`, label: `Grid Points`, type: `number`, default: 2000, group: `DOS Parameters`,
      min: 100, max: 10000, step: 100,
      help: `Number of energy grid points for interpolation.`,
    },
    // --- Atom selection ---
    { key: `atom_indices`, label: `Atom Indices`, type: `string`, default: ``, group: `Atom Selection`,
      help: `Comma-separated atom indices for PDOS (empty = all atoms). Example: "0,1,2,3"`,
    },
    { key: `element_filter`, label: `Element Filter`, type: `string`, default: ``, group: `Atom Selection`,
      help: `Filter atoms by element (e.g. "Fe" or "Ti,O"). Empty = all elements.`,
    },
    { key: `orbital_channels`, label: `Orbital Channels`, type: `select`, default: `total`, group: `Orbitals`,
      options: [
        { label: `Total`, value: `total` },
        { label: `s`, value: `s` },
        { label: `p`, value: `p` },
        { label: `d`, value: `d` },
        { label: `f`, value: `f` },
        { label: `s+p+d`, value: `s+p+d` },
      ],
      help: `Which orbital channels to project onto.`,
    },
    // --- d-band ---
    { key: `d_band`, label: `Compute d-Band Center`, type: `boolean`, default: true, group: `D-Band`,
      help: `Calculate d-band center, width, and filling for transition metals.`,
    },
    { key: `d_band_occupied_only`, label: `Occupied States Only`, type: `boolean`, default: true, group: `D-Band`,
      show_if: { key: `d_band`, values: [`true`, true] },
      help: `Only include states below Fermi level for d-band center.`,
    },
  ],
}
